-- Stergem tabelele dacă exista (ordinea inversa)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE cbReteta CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE cbProgramare CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE cbMedic CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE cbGrad CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE cbSpecialitate CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Creare tabele

CREATE TABLE cbSpecialitate (
    codSpec VARCHAR2(10) PRIMARY KEY,
    denumire VARCHAR2(100) NOT NULL,
    coefPlata NUMBER(3,2) NOT NULL
);

CREATE TABLE cbGrad (
    codGrad VARCHAR2(5) PRIMARY KEY,
    denumire VARCHAR2(50) NOT NULL,
    tarif NUMBER(10,2) NOT NULL
);

CREATE TABLE cbMedic (
    medID VARCHAR2(10) PRIMARY KEY,
    nume VARCHAR2(100) NOT NULL,
    codSpec VARCHAR2(10) NOT NULL,
    codGrad VARCHAR2(5) NOT NULL,
    CONSTRAINT fk_codSpec FOREIGN KEY (codSpec) REFERENCES cbSpecialitate(codSpec),
    CONSTRAINT fk_codGrad FOREIGN KEY (codGrad) REFERENCES cbGrad(codGrad)
);

CREATE TABLE cbProgramare (
    codPro VARCHAR2(10) PRIMARY KEY,
    data DATE NOT NULL,
    cnp VARCHAR2(13) NOT NULL,
    nume VARCHAR2(100) NOT NULL,
    medID VARCHAR2(10) NOT NULL,
    cabinet VARCHAR2(10) NOT NULL,
    CONSTRAINT fk_medID FOREIGN KEY (medID) REFERENCES cbMedic(medID)
);

CREATE TABLE cbReteta (
    codPro VARCHAR2(10) NOT NULL,
    nrItem NUMBER NOT NULL,
    medicament VARCHAR2(100) NOT NULL,
    doza_zi VARCHAR2(20) NOT NULL,
    durata_zile NUMBER NOT NULL,
    PRIMARY KEY (codPro, nrItem),
    CONSTRAINT fk_codPro FOREIGN KEY (codPro) REFERENCES cbProgramare(codPro)
);
